---
title: "Rstan und brms installieren"
description: |
  Eine Anleitung zur Installation der `rstan` und `brms` R packages.
author:
  - first_name: "Andrew"
    last_name: "Ellis"
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation_url: https://www.kog.psy.unibe.ch
    orcid_id: 0000-0002-2788-936X
date: 03-02-2021
categories:
  - rstan
  - brms
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Für das Beispiel am Ende der 2. Sitzung brauchen sie [rstan](https://mc-stan.org/rstan/) und [brms](https://paul-buerkner.github.io/brms/). Bevor Sie diese installieren, sollten sie einen C++ Compiler installieren. Die Anleitungen für Windows, MacOS und Linux finden Sie hier:
[https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain).

Wenn Sie Hilfen benötigen, bitte im [#troubleshooting Stream](https://neuroscicomputerlab.zulipchat.com/#narrow/stream/278490-troubleshooting) in Zulip fragen.

Wenn Sie die C++ Toolchain installiert haben, können Sie `rstan` und `brms` installieren:

```{r eval=FALSE, include=TRUE}
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages("brms")
```



