---
title: "Leistungskontrollen"
description: |
  Es gibt wöchentliche Übungen. Davon müssen __6__ Übungen abgegeben werden. Welche dies sind wird im Verlaufe des Semesters bekanntgegeben.
author:
  - first_name: "Andrew"
    last_name: "Ellis"
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation_url: https://www.kog.psy.unibe.ch
    orcid_id: 0000-0002-2788-936s
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Leistungskontrolle
<!-- `r fontawesome::fa(name = "grin-beam-sweat", fill = "steelblue")`  -->

Leistungskontrollen werden in Form von Übungen erbracht. Es gibt wöchentliche Übungen. Davon müssen __6__ Übungen abgegeben werden. Welche dies sind wird im Verlaufe des Semesters bekanntgegeben.

Der Zweck dieser Übungen ist, das Gelernte selber anzuwenden, oder dies zumindest zu versuchen. Es gibt für viele dieser Übungen nicht eine definitive, richtige Antwort - es geht vor allem darum, es selber zu versuchen. Bei einzureichenden Übungen gibt es die Möglichkeit, diese falls nötig (nach Verbesserung) ein zweites Mal einzureichen.

Die Übungen sollen jeweils in dem entsprechenden Ordner auf ILIAS hochgeladen werden, und zwar in Form eines R Scripts, oder als [Rmarkdown](rmarkdown.html) File.

ILIAS (Vormittag) 👉 [468703-FS2022-0](https://ilias.unibe.ch/ilias.php?ref_id=2303490&cmd=frameset&cmdClass=ilrepositorygui&cmdNode=11o&baseClass=ilrepositorygui#il_mhead_t_focus)

ILIAS (Nachmittag) 👉 [468703-FS2022-1](https://ilias.unibe.ch/ilias.php?ref_id=2327460&cmd=frameset&cmdClass=ilrepositorygui&cmdNode=11o&baseClass=ilrepositorygui#il_mhead_t_focus)

<aside> Ein gute Einführung in [Rmarkdown](https://rmarkdown.rstudio.com/) finden Sie z.B. [hier](https://rmd4sci.njtierney.com/).</aside>


Falls Datenfiles dazugehören, sollte unbedingt alles in einem ZIP File komprimiert werden. Sie können auch eine Word/Libreoffice Datei abgeben; _bitte fügen Sie aber keinen R Code in ein Word Dokument ein_.




