---
title: "Zulip Diskussionforum"
description: |
  Für Fragen, technischen Support, etc.
author:
  - first_name: "Andrew"
    last_name: "Ellis"
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation_url: https://www.kog.psy.unibe.ch
    orcid_id: 0000-0002-2788-936X

citation_url: https://kogpsy.github.io/neuroscicomplabFS22/zulip.html
# slug: ellis2021overview
# bibliography: bibliography.bib
output: 
    distill::distill_article:
      toc: true
      toc_float: true
      toc_depth: 2
      code_folding: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



Wir benutzen in dieser Veranstaltung [Zulip](https://neuroscicomplab2022.zulipchat.com/) als Diskussionforum. Zulip hat einige Vorteile gegenüber ILIAS und Email:

- Zulip ist besser geeignet, um Code darzustellen.
- Wir benutzen dasselbe Forum für die Vormittags- und Nachmittagsveranstaltungen.
- Die Diskussion ist für alle Teilnehmer sichtbar. 
- Diskussion kann in Echtzeit (synchron) oder offline (asynchron) stattfinden.

Bitte erstellen Sie unter diesem Link einen Account. Sie müssen dafür Ihre Uni Emailadresse verwenden.
Account erstellen 👉 [zulipchat.com/join/hyuinbg3mtcumccnzt3tpsqb/](https://neuroscicomplab2022.zulipchat.com/join/yccpwafelyhogs2zv5qhiwlt/)

<br>
Wenn Sie einen Account erstellt haben, können Sie sich unter folgendem Link einloggen.
Zulip Forum 👉 [neuroscicomplab2022.zulipchat.com](https://neuroscicomplab2022.zulipchat.com/")

Ausserdem ist Zulip als Desktop oder Mobile App für alle gängigen Betriebssysteme erhältlich.
Apps 👉 [zulip.com/apps](https://zulip.com/apps/)