---
title: "Online Experiment"
description: |
  Mentale Rotation unter verschiedenen Strategien.
author:
  - name: Gerda Wyssen
    url: https://github.com/awellis
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Für die nächste Übung werden Sie gebeten an einem Online-Experiment teilzunehmen. Oft ist es einfacher Daten zu analysieren, wenn man den Task mit dem sie erhoben wurden gut kennt. Dies hilft bei der Interpretation der Daten und dem Verstehen, was die Parameter genau beschreiben.

Das Online-Experiment besteht aus einer mentalen Rotationsaufgabe, welche mit zwei verschiedenen Strategien gelöst werden muss. Mentale Rotationen sind in unserem Alltag wichtig, um z.B. einem Freund den Weg aus seiner Perspektive zu erklären oder ein Werkzeug in die richtige Ausgangsposition zu bringen. Diese Studie dient dazu den Einfluss verschiedener Strategien auf mentale Rotationen zu untersuchen. 

:::note
Diese Aufgabe ermöglicht keine Rückschlüsse auf die Person oder spezifische Eigenschaften über den Task hinaus. Bitte lesen Sie die Einverständniserklärung durch und klicken Sie anschliessend auf den Link. Sie dürfen Angaben zu Ihrer Person machen müssen jedoch nicht, dann können Sie stattdessen einfach in jedes Feld ein *X* schreiben. Bitte geben Sie **nicht** falsche Angaben an. Wir freuen uns sehr über Angaben zur Person, dies ermöglicht es uns, die Daten in unserer Forschung zu verwenden und Sie zu publizieren. Daten mit einem *X* werden nur für diesen Kurs verwendet und anschliessend gelöscht.
:::

## Infos zum Online Experiment

Vielen herzlichen Dank für die Teilnahme am Experiment!

Einige wichtige Punkte für die Durchführung:

- Bitte führen Sie die Studie an einem Computer durch (nicht am Tablet oder Handy), da ein grösserer Bildschirm und eine Tastatur erforderlich sind.

- Bitte sorgen Sie dafür, dass Sie für den Zeitraum des Experiments ungestört sind. Führen Sie das Experiment bitte an einem Stück und konzentriert durch.

- Das Experiment läuft am besten auf Firefox, Microsoft Edge oder Safari. Andere Browser haben teilweise Schwierigkeiten das Experiment anzuzeigen.

- Lesen Sie bitte die Information & Einverständnis durch, danach können Sie auf den Link klicken.


## Information zur Teilnahme an der Studie und Einverständnis

Vielen Dank für das Interesse und die Teilnahmebereitschaft an dieser Studie. Bevor Sie sich bereit erklären, an der Studie teilzunehmen, ist es wichtig, dass Sie die folgenden Erklärungen genau durchlesen. Ihnen wird der Zweck dieser Studie erklärt, ebenso die Prozedur mit dazugehörigen Risiken, Unannehmlichkeiten und Vorsichtsmassnahmen.  

Das Experiment dauert ungefähr 30 Minuten und beinhaltet Fragen zur Person und eine Rotationsaufgabe, welche mit unterschiedlichen Strategien gelöst werden soll. Für diese Studie gibt es keine Ausschlusskriterien. Die Teilnahme an der Studie stellt kein uns bekanntes Risiko dar.

Die Teilnahme an der Studie ist freiwillig und kann jederzeit und ohne Begründung abgebrochen werden. Hierbei entstehen für die Teilnehmenden keine Nachteile. Diese Studie wurde durch die Ethik-Kommission der philosophisch-humanwissenschaftlichen Fakultät der Universität Bern genehmigt. Bei Fragen oder Bedenken dürfen Sie sich jederzeit an die Studienleiterin wenden: [gerda.wyssen@psy.unibe.ch](mailto:gerda.wyssen@psy.unibe.ch). 

Mit der Teilnahme bestätigen Sie, dass Sie schriftlich über die Ziele, den Ablauf der Studie, über die zu erwartenden Wirkungen, über mögliche Vor-und Nachteile sowie über eventuelle Risiken informiert wurden und dass Sie die oben genannten Studie abgegebene schriftliche Information gelesen und verstanden haben. Zudem, dass Ihre Fragen im Zusammenhang mit der Teilnahme zufriedenstellend beantwortet worden sind, und Sie genügend Zeit hatten, die Entscheidung zu treffen, an der Studie teilzunehmen.Sie wurden in Kenntnis gesetzt, dass Ihre Daten nur in pseudonymisierter Form gespeichert werden. Die Resultate können im Kurs ausgewertet und aus wissenschaftlichen Gründen veröffentlicht werden, wobei die Anonymität aller Teilnehmer gewahrt bleibt. Jede Versuchsperson kann bis zum Ende der Datenerhebung die Löschung ihrer personenbezogenen Daten verlangen. Nach Ende der Datenerhebung wird die Zuordnungsliste vernichtet und die erhobenen Daten können nicht mehr den einzelnen Versuchspersonen zugeordnet, und daher auch nicht mehr gelöscht werden. Mitglieder der zuständigen Ethikkommission zu Prüf-und Kontrollzwecken können Einsicht nehmen unter strikter Einhaltung der Vertraulichkeit. Sie nehmen an dieser Studie freiwillig teil. Sie können jederzeit und ohne Angabe von Gründen Ihre Zustimmung zur Teilnahme widerrufen, ohne dass Ihnen deswegen Nachteile entstehen. 


## Link zum Experiment

Klicken Sie bitte auf den untenstehenden Link und befolgen Sie bitte die Anweisungen, die Sie dort vorfinden. Bei *participant* können Sie eine 5-stellige Zahl eingeben.

**Legen Sie den linken Zeigefinger auf die linke Pfeiltaste und den rechten Zeigefinger auf die rechte Pfeiltaste um die Aufgabe zu lösen**

**Lösen Sie die Aufgaben jeweils so schnell wie möglich**

[**Online Experiment Mentale Rotation**](https://run.pavlovia.org/Wyssen/navigation2)


:::note
Falls Sie beim Öffnen oder Durchführen des Experiments Probleme haben, melden Sie sich bitte auf Zulip.
:::
