---
title: "Übung 1"
description: | 
    PsychoPy installieren.
date: "2022-02-22"
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
license: CC BY
citation: true
bibliography: ../../bibliography.bib
format:
    html:
        toc: true
        code-link: true
---

# Aufgabenstellung

:::{.callout-note}
Diese Übung muss nicht abgegeben werden; sie dient als Vorbereitung für die folgende Sitzung.
:::

## Aufgabe 1

Installieren Sie [PsychoPy](https://www.psychopy.org) von der Website. PsychoPy ist ein Open-Source Programm für MacOS, Windows und Linux, mit welchen wir sehr viele verschiedene Verhaltensexperimente (Neuroscience, Psychologie, Psychophysik, Linguistik) programmieren können. Diese lassen sich z.B. mit Eyetracking verbinden, oder im fRMI Scanner und mit EEG verwenden.

PsychoPy 👉 [https://www.psychopy.org/download.html](https://www.psychopy.org/download.html). 

Am einfachsten ist es, das "Standalone package" für MacOS oder Windows zu installieren. 

<aside>
  Unter MacOS scheint die neueste Version vom Februar 2022 Probleme zu bereiten --- es ist daher (zurzeit noch) besser, die Version **2021.2.3** zu installieren.
</aside>

## Aufgabe 2 

1) Was verstehen Sie unter folgenen Begriffen:
  - Model-based Neuroscience
  - Evidence accumulation

2) Was könnte man unter Vorwissen (prior knowledge) verstehen? In welchen Kontexten könnte es bei Entscheidungen nützlich sein, Vorwissen zu benutzen?